<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>14</LangVersion>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <InterceptorsNamespaces>$(InterceptorsNamespaces);GameKit.DependencyInjection.Generated</InterceptorsNamespaces>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="ppy.SDL3_mixer-CS" Version="2026.520.0" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\GameKit.Common\GameKit.Common.csproj" />
        <ProjectReference Include="..\GameKit\GameKit.csproj" />
        <ProjectReference Include="..\GameKit.DependencyInjection\GameKit.DependencyInjection.csproj" />
        <ProjectReference Include="..\GameKit.DependencyInjection.Generator\GameKit.DependencyInjection.Generator.csproj"
                          OutputItemType="Analyzer"
                          ReferenceOutputAssembly="false" />
    </ItemGroup>

</Project>
