path: "**/*.cs"
tone_instructions: "Focus on code issues, avoid refactoring suggestions."
reviews:
  request_changes_workflow: false
  high_level_summary: false
  poem: false
  review_status: false
  changed_files_summary: false
  collapse_walkthrough: false
  auto_review:
    enabled: false
    drafts: false
