<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="../GameKit.Common/GameKit.Common.csproj" />
        <ProjectReference Include="../GameKit.Collections/GameKit.Collections.csproj" />
    </ItemGroup>

</Project>
