<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <LangVersion>14</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <InterceptorsNamespaces>$(InterceptorsNamespaces);GameKit.DependencyInjection.Generated</InterceptorsNamespaces>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\GameKit.DependencyInjection\GameKit.DependencyInjection.csproj" />
      <ProjectReference Include="..\GameKit.DependencyInjection.Generator\GameKit.DependencyInjection.Generator.csproj"
                        OutputItemType="Analyzer"
                        ReferenceOutputAssembly="false" />
    </ItemGroup>

    <Import Project="..\GameKit.DependencyInjection.Generator\build\GameKit.DependencyInjection.Generator.props" />

</Project>
