<Project>
    <PropertyGroup>
        <InterceptorsNamespaces>$(InterceptorsNamespaces);Pixely.DependencyInjection.Generated</InterceptorsNamespaces>
        <SdlangCompilerAssembly>$(MSBuildThisFileDirectory)..\tools\net10.0\any\Pixely.SdlangCompiler.dll</SdlangCompilerAssembly>
        <SlangToolRoot>$(MSBuildThisFileDirectory)..\tools\slang\</SlangToolRoot>
    </PropertyGroup>

    <ItemGroup>
        <CompilerVisibleProperty Include="PixelyDIEmitTrimAnnotations" />
    </ItemGroup>

    <Import Project="$(MSBuildThisFileDirectory)..\tools\net10.0\any\build\Pixely.SdlangCompiler.props" />
</Project>
