<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>14</LangVersion>
    </PropertyGroup>

    <PropertyGroup>
        <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
      <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
      <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="MessagePack" Version="3.1.0" />
      <PackageReference Include="ppy.SDL3-CS" Version="2026.302.0" />
      <ProjectReference Include="..\..\..\Yak\src\Yak\Yak.csproj" />
      <ProjectReference Include="..\..\..\Yak\src\Yak.Generator\Yak.Generator.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
      <PackageReference Include="ppy.SDL3_image-CS" Version="2026.302.0" />
      <PackageReference Include="ppy.SDL3_ttf-CS" Version="2026.302.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\GameKit.Collections\GameKit.Collections.csproj" />
      <ProjectReference Include="..\GameKit.Common\GameKit.Common.csproj" />
      <ProjectReference Include="..\GameKit.Encs\GameKit.Encs.csproj" />
      <ProjectReference Include="..\GameKit.ShaderCommon\GameKit.ShaderCommon.csproj" />
    </ItemGroup>

</Project>
