<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>14</LangVersion>
        <InterceptorsNamespaces>$(InterceptorsNamespaces);GameKit.DependencyInjection.Generated</InterceptorsNamespaces>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
    </PropertyGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="GameKit.Tests" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="ppy.SDL3-CS" Version="2026.629.0" />
      <PackageReference Include="ppy.SDL3_image-CS" Version="2026.629.0" />
      <PackageReference Include="ppy.SDL3_ttf-CS" Version="2026.629.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\GameKit.Collections\GameKit.Collections.csproj" />
      <ProjectReference Include="..\GameKit.DependencyInjection\GameKit.DependencyInjection.csproj" />
      <ProjectReference Include="..\GameKit.DependencyInjection.Generator\GameKit.DependencyInjection.Generator.csproj"
                        OutputItemType="Analyzer"
                        ReferenceOutputAssembly="false" />
      <ProjectReference Include="..\GameKit.Core\GameKit.Core.csproj" />
      <ProjectReference Include="..\GameKit.ShaderCommon\GameKit.ShaderCommon.csproj" />
    </ItemGroup>

</Project>
